on:
  push:
    branches:
      - master
      - release/v*
    tags:
      - 'v*.*.*'
    paths-ignore:
      - README.md
      - LICENSE
      - .travis.yml
      - .azure-pipeline.yml
      - templates/azure/*

name: Release

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Set up Go 1.15
        id: go
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
      - name: Check out code
        uses: actions/checkout@v2.3.3
        with:
          fetch-depth: 0
      - name: GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}